continuum:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint1z
    pid: {p: 0.0001, i: 0.0001, d: 0.0001}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint1x
    pid: {p: 0.0001, i: 0.0001, d: 0.0001}
  # joint3_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: joint2z
  #   pid: {p: 1.0, i: 0.0, d: 0.0}
  # joint4_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: joint2x
  #   pid: {p: 1.0, i: 0.0, d: 0.0}
  # joint5_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: joint3z
  #   pid: {p: 1.0, i: 0.0, d: 0.0}
  # joint6_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: joint3x
  #   pid: {p: 1.0, i: 0.0, d: 0.0}
  # joint7_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: joint4z
  #   pid: {p: 1.0, i: 0.0, d: 0.0}
  # joint8_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: joint4x
  #   pid: {p: 1.0, i: 0.0, d: 0.0}
  # joint9_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: joint5z
  #   pid: {p: 1.0, i: 0.0, d: 0.0}
  # joint10_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: joint5x
  #   pid: {p: 1.0, i: 0.0, d: 0.0}
  # joint11_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: joint6z
  #   pid: {p: 1.0, i: 0.0, d: 0.0}
  # joint12_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: joint6x
  #   pid: {p: 1.0, i: 0.0, d: 0.0}
  # joint13_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: joint7z
  #   pid: {p: 1.0, i: 0.0, d: 0.0}
  # joint14_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: joint7x
  #   pid: {p: 1.0, i: 0.0, d: 0.0}
